-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 21:03:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EmployeeDB
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Fname` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;




-- -----------------------------------------------------
-- Table `mydb`.`Buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Buyer` (
  `B_ID` INT(11) NOT NULL,
  `Wallet` INT(11) NOT NULL,
  PRIMARY KEY (`B_ID`),
  INDEX `fk_Buyer_User1_idx` (`B_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Charity_Organizator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Charity_Organizator` (
  `C_ID` INT(11) NOT NULL,
  PRIMARY KEY (`C_ID`),
  INDEX `fk_Charity_Organizator_User1_idx` (`C_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Charity_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Charity_event` (
  `Ch_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Purpose` VARCHAR(45) NOT NULL,
  `Amount` INT(11) NOT NULL,
  `Charity_Organizator_C_ID` INT(11) NULL DEFAULT NULL,
  `Goal` INT(11) NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Ch_ID`),
  INDEX `fk_Charity_event_Charity Organizator1_idx` (`Charity_Organizator_C_ID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Donator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Donator` (
  `D_ID` INT(11) NOT NULL,
  PRIMARY KEY (`D_ID`),
  INDEX `fk_table3_User1_idx` (`D_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Reviewer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reviewer` (
  `R_ID` INT(11) NOT NULL,
  PRIMARY KEY (`R_ID`),
  INDEX `fk_Reviewer_User1_idx` (`R_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Donated_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Donated_item` (
  `I_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Price` INT(11) NOT NULL,
  `Date_of_admission` DATETIME NOT NULL,
  `Size` INT(11) NULL DEFAULT NULL,
  `Reviews` VARCHAR(45) NULL DEFAULT NULL,
  `Buyer_B_ID` INT(11) NULL DEFAULT NULL,
  `Donator_D_ID` INT(11) NULL DEFAULT NULL,
  `Reviewer_R_ID` INT(11) NULL DEFAULT NULL,
  `Status` VARCHAR(200) NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`I_ID`),
  INDEX `fk_Donated_item_Buyer1_idx` (`Buyer_B_ID` ASC),
  INDEX `fk_Donated_item_Donator1_idx` (`Donator_D_ID` ASC),
  INDEX `fk_Donated_item_Reviewer1_idx` (`Reviewer_R_ID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Charity_event_has_Buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Charity_event_has_Buyer` (
  `Charity_event_Ch_ID` INT(11) NOT NULL,
  `Buyer_B_ID` INT(11) NOT NULL,
  `Donation_amount` INT NOT NULL,
  PRIMARY KEY (`Charity_event_Ch_ID`, `Buyer_B_ID`),
  INDEX `fk_Charity_event_has_Buyer_Buyer1_idx` (`Buyer_B_ID` ASC),
  INDEX `fk_Charity_event_has_Buyer_Charity_event1_idx` (`Charity_event_Ch_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
